services:
  - type: web
    name: 13store-metaverse
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 online_server.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
